// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'minScaleItemWidth': string;
  'rootFontSize': string;
  'thumbHeight': string;
  'thumbWidth': string;
  'topOffset': string;
  'trackHeight': string;
}
export const cssExports: CssExports;
export default cssExports;
